set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

get_filename_component(BUILD_ROOT "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
set(LLVM_MINGW "${BUILD_ROOT}/llvm-mingw-20260908-msvcrt-ubuntu-22.04-x86_64")
set(MSYS_PREFIX "${BUILD_ROOT}/msysroot/mingw64")
set(WIN_PREFIX "${BUILD_ROOT}/winprefix")

set(CMAKE_C_COMPILER "${LLVM_MINGW}/bin/x86_64-w64-mingw32-clang")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW}/bin/x86_64-w64-mingw32-clang++")
set(CMAKE_RC_COMPILER "${LLVM_MINGW}/bin/x86_64-w64-mingw32-windres")
set(CMAKE_AR "${LLVM_MINGW}/bin/x86_64-w64-mingw32-ar")
set(CMAKE_RANLIB "${LLVM_MINGW}/bin/x86_64-w64-mingw32-ranlib")
set(CMAKE_STRIP "${LLVM_MINGW}/bin/x86_64-w64-mingw32-strip")

set(CMAKE_FIND_ROOT_PATH "${WIN_PREFIX}" "${MSYS_PREFIX}" "${LLVM_MINGW}/x86_64-w64-mingw32")
set(CMAKE_PREFIX_PATH "${WIN_PREFIX}" "${MSYS_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
